# Shell variables
# Generated by 'wal'
wallpaper="/home/spy/dotfiles2/wallpaper/nordic-wallpapers/ign_unsplash7.png"

# Special
background='#08090b'
foreground='#c1c1c2'
cursor='#c1c1c2'

# Colors
color0='#08090b'
color1='#7699B1'
color2='#7A9BC3'
color3='#A18480'
color4='#859AAA'
color5='#9C9AA3'
color6='#CDB2A9'
color7='#c1c1c2'
color8='#454648'
color9='#7699B1'
color10='#7A9BC3'
color11='#A18480'
color12='#859AAA'
color13='#9C9AA3'
color14='#CDB2A9'
color15='#c1c1c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
