--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/spy/dotfiles2/wallpaper/nordic-wallpapers/ign_unsplash7.png"

-- Special
background="#08090b"
foreground="#c1c1c2"
cursor="#c1c1c2"

-- Colors
color0="#08090b"
color1="#7699B1"
color2="#7A9BC3"
color3="#A18480"
color4="#859AAA"
color5="#9C9AA3"
color6="#CDB2A9"
color7="#c1c1c2"
color8="#454648"
color9="#7699B1"
color10="#7A9BC3"
color11="#A18480"
color12="#859AAA"
color13="#9C9AA3"
color14="#CDB2A9"
color15="#c1c1c2"
