--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/spy/dotfiles2/wallpaper/mounten-2mon.jpg"

-- Special
background="#020304"
foreground="#bfc0c0"
cursor="#bfc0c0"

-- Colors
color0="#020304"
color1="#518CDC"
color2="#5494E4"
color3="#659FE1"
color4="#6FB0F0"
color5="#7CBDF4"
color6="#88B6E3"
color7="#bfc0c0"
color8="#414242"
color9="#518CDC"
color10="#5494E4"
color11="#659FE1"
color12="#6FB0F0"
color13="#7CBDF4"
color14="#88B6E3"
color15="#bfc0c0"
