--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/spy/.dotfiles/wallpapers/a.png"

-- Special
background="#000203"
foreground="#bfbfc0"
cursor="#bfbfc0"

-- Colors
color0="#000203"
color1="#6C8A5D"
color2="#7F9C6F"
color3="#699494"
color4="#58B9C7"
color5="#93B3AB"
color6="#AEC8B5"
color7="#bfbfc0"
color8="#3f4142"
color9="#6C8A5D"
color10="#7F9C6F"
color11="#699494"
color12="#58B9C7"
color13="#93B3AB"
color14="#AEC8B5"
color15="#bfbfc0"
