# Shell variables
# Generated by 'wal'
wallpaper="/usr/share/backgrounds/nordic-wallpapers/mountain_jaws.jpg"

# Special
background='#020305'
foreground='#bfc0c0'
cursor='#bfc0c0'

# Colors
color0='#020305'
color1='#737985'
color2='#7C828E'
color3='#9AA0AC'
color4='#B4BAC6'
color5='#BDC3CF'
color6='#C7CDD9'
color7='#bfc0c0'
color8='#414243'
color9='#737985'
color10='#7C828E'
color11='#9AA0AC'
color12='#B4BAC6'
color13='#BDC3CF'
color14='#C7CDD9'
color15='#bfc0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
