# Shell variables
# Generated by 'wal'
wallpaper="/home/spy/dotfiles2/wallpaper/mounten-2mon.jpg"

# Special
background='#020304'
foreground='#bfc0c0'
cursor='#bfc0c0'

# Colors
color0='#020304'
color1='#518CDC'
color2='#5494E4'
color3='#659FE1'
color4='#6FB0F0'
color5='#7CBDF4'
color6='#88B6E3'
color7='#bfc0c0'
color8='#414242'
color9='#518CDC'
color10='#5494E4'
color11='#659FE1'
color12='#6FB0F0'
color13='#7CBDF4'
color14='#88B6E3'
color15='#bfc0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
