--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/nordic-wallpapers/mountain_jaws.jpg"

-- Special
background="#020305"
foreground="#bfc0c0"
cursor="#bfc0c0"

-- Colors
color0="#020305"
color1="#737985"
color2="#7C828E"
color3="#9AA0AC"
color4="#B4BAC6"
color5="#BDC3CF"
color6="#C7CDD9"
color7="#bfc0c0"
color8="#414243"
color9="#737985"
color10="#7C828E"
color11="#9AA0AC"
color12="#B4BAC6"
color13="#BDC3CF"
color14="#C7CDD9"
color15="#bfc0c0"
